2022-07-11 11:28:27,411 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    listIntc.append(intc[0])
IndexError: list index out of range
2022-07-11 11:28:54,084 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-07-11 11:29:06,216 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 87, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 11:30:37,250 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-07-12 08:15:35,007 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 88, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-14 23:53:21,410 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-07-15 22:45:49,331 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 60, in parsHosts
    listIntcItem = zabxmax.getDirnIntcItem(host_A, False, 'Admin status', value=0, zabx=zabx)   #получаем список item по Admin status для получения host_B
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 163, in getDirnIntcItem
    items = zabx.item.get(hostids=hostID_A,
AttributeError: 'NoneType' object has no attribute 'item'
2022-07-15 22:46:47,378 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 60, in parsHosts
    listIntcItem = zabxmax.getDirnIntcItem(host_A, False, 'Admin status', value=0, zabx=zabx)   #получаем список item по Admin status для получения host_B
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 163, in getDirnIntcItem
    items = zabx.item.get(hostids=hostID_A,
AttributeError: 'NoneType' object has no attribute 'item'
2022-07-15 22:54:19,636 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-08-24 17:11:58,230 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-08-24 20:21:56,307 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 18:31:51,702 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 18:35:16,380 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 22:57:02,940 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 23:16:05,927 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
